---
title: "Preferring Politeness - Sample Statistical Analyses"
output: html_document
---

```{r setup, include = F}
knitr::opts_chunk$set(echo = TRUE)
```

```{r lsetup}
library(rstanarm)
library(tidyverse)
library(dplyr)
library(remotes)
library(binom)
library(Bolstad)
library(pwr)
library(generics)
library(raster)
library(tibble)
library(LaplacesDemon)
library(scales)
library(BayesFactor)
library(BayesianFirstAid)

theme_set(theme_classic())

knitr::write_bib(.packages(), "references/packages.bib")
```

```{r load_data}
pp_data = read.csv("sample_data.csv")
```

```{r wrangling}
pp_data$speaker_preference[pp_data$speaker_preference == "polite"] <- 1
pp_data$speaker_preference[pp_data$speaker_preference == "impolite"] <- 0

pp_data <- pp_data %>% 
  subset(speaker_preference != "none") %>%
  drop_na(age) %>% 
  mutate(across(.cols = c(speaker_preference, 
                          age),
                .fns = ~ as.numeric(.)))

View(pp_data)
```

```{r count_speaker_preference}
speaker_matrix <- table(pp_data$age_category, 
                        pp_data$speaker_preference)
print(speaker_matrix)
```

```{r verify_data_type}
is.matrix(speaker_matrix)
```

```{r binomial_test}
binomial_test = bayes.binom.test(x = speaker_matrix["2","1"] + speaker_matrix["3","1"] + speaker_matrix["4","1"], 
                                  n = nrow(pp_data), 
                                  comp.theta = .5, 
                                  cred.mass = .95)
binomial_test
```

```{r binomial_test_2}
binomial_test2 = bayes.binom.test(x = speaker_matrix["2","1"],
                                  n = speaker_matrix["2","0"] + speaker_matrix["2","1"],
                                  comp.theta = .5,
                                  cred.mass = .95)
binomial_test2
```

```{r binomial_test_3}
binomial_test3 = bayes.binom.test(x = speaker_matrix["3","1"],
                                  n = speaker_matrix["3","0"] + speaker_matrix["3","1"], 
                                  comp.theta = .5, 
                                  cred.mass = .95)
binomial_test3
```

```{r binomial_test_4}
binomial_test4 = bayes.binom.test(x = speaker_matrix["4","1"],
                                  n = speaker_matrix["4","0"] + speaker_matrix["4","1"], 
                                  comp.theta = .5, 
                                  cred.mass = .95)
binomial_test4
```

```{r binomial_test_2v3}
binomial_test2v3 = bayes.binom.test(x = speaker_matrix["2","1"],
                                  n = speaker_matrix["2","0"] + speaker_matrix["2","1"],
                                  comp.theta = mean(pp_data$speaker_preference[pp_data$age_category == 3]),
                                  cred.mass = .95)
binomial_test2v3
```

```{r binomial_test3v4}
binomial_test3v4 = bayes.binom.test(x = speaker_matrix["3","1"],
                                     n = speaker_matrix["3","0"] + speaker_matrix["3","1"],
                                     comp.theta = mean(pp_data$speaker_preference[pp_data$age_category == 4]), 
                                     cred.mass = .95)
binomial_test3v4
```

```{r binomial_test_2v4}
binomial_test2v4 = bayes.binom.test(x = speaker_matrix["2","1"],
                                    n = speaker_matrix["2","0"] + speaker_matrix["2","1"],
                                    comp.theta = mean(pp_data$speaker_preference[pp_data$age_category == 4]),
                                    cred.mass = .95)
binomial_test2v4
```

```{r count_biases}
# Create frequency matrices to pull values from when running binomial tests

shape_matrix = table(pp_data$shape_preference)
print(shape_matrix)

color_matrix = table(pp_data$color_preference)
print(color_matrix)

order_matrix = table(pp_data$order_preference)
print(order_matrix)

side_matrix = table(pp_data$side_preference)
print(side_matrix)
```

```{r binomial_test_shape}
binomial_test_shape = bayes.binom.test(x = shape_matrix["1"], 
                                       n = shape_matrix["1"] + shape_matrix["2"], 
                                       comp.theta = .5, 
                                       cred.mass = .95)
binomial_test_shape
```

```{r binomial_test_color}
binomial_test_color = bayes.binom.test(x = color_matrix["1"], 
                                       n = color_matrix["1"] + color_matrix["2"], 
                                       comp.theta = 0.5, 
                                       cred.mass = 0.95)
binomial_test_color
```

```{r binomial_test_order}
binomial_test_order = bayes.binom.test(x = order_matrix["1"], 
                                       n = order_matrix["1"] + order_matrix["2"], 
                                       comp.theta = .5, 
                                       cred.mass = .95)
binomial_test_order
```

```{r binomial test side bias}
binomial_test_side = bayes.binom.test(x = side_matrix["1"], 
                                      n = side_matrix["1"] + side_matrix["2"], 
                                      comp.theta = .5, 
                                      cred.mass = .95)
binomial_test_side
```

We intend to run two Bayesian logistic regression models from the rstanarm package to:

1. Model speaker preference (DV1) as a function of age.
2. Model reasoning (DV2, inclusive of reasoning levels 1 - 3) as a function of age.

```{r DV1_logisitc_regression}
DV1_model = stan_glm(speaker_preference~age, 
                     family = binomial(), 
                     data = pp_data)
```

```{r visualize DV1 logistic model}
DV1.y.fit <- fitted(DV1_model)

ggplot(pp_data, 
       aes(x = age)) +
  geom_jitter(aes(y = speaker_preference,
                  col = age_category),
              size = 3, 
              height = 0.03, 
              alpha = 0.5) +
  scale_color_gradient(low = "blue",
                        high = "red") +
  geom_smooth(aes(y = DV1.y.fit), 
              size = 1, 
              alpha = 0.5,
              color = "black") +
  theme(legend.position = "none") +
  scale_y_continuous(breaks = c(0, 1)) +
  labs(title = "Speaker preference as a function of age",
       x = "Age (years)", 
       y = "Speaker preference")

ggsave(filename = "vis1.png", path = "C:/Users/Hannah/Desktop/preferring_politeness/figures/plots")
```

```{r}
DV1_model_2 = stan_glm(speaker_preference~age, 
                     family = binomial(), 
                     data = pp_data)


```

```{r visualize DV1 logistic model}
DV1.y.fit <- fitted(DV1_model)


ggplot(pp_data, 
       aes(x = age, y = speaker_preference)) +
  geom_jitter(aes(col = age_category),
              size = 3, 
              height = 0.03, 
              alpha = 0.5) +
  scale_color_gradient(low = "blue",
                        high = "red") +
 geom_smooth(method = glm, 
              size = 1, 
              alpha = 0.5,
              color = "black") +
  theme(legend.position = "none") +
  facet_grid(cols = vars(age_category),
             scales = "free_x") +
  scale_y_continuous(breaks = c(0, 1)) +
  labs(title = "Speaker preference as a function of age",
       x = "Age (years)", 
       y = "Speaker preference")
```

```{r visualize DV1 logistic model}
theme_set(theme_classic() +
            theme(plot.tag = element_text(face = "bold", 
                                          size = 15)))

ggplot(pp_data, aes(x=age_category, y = speaker_preference)) +
  geom_bar(stat = "summary") +
  geom_jitter(aes(x = age, y = speaker_preference), 
              size = 3, 
              height = 0.03,
              alpha = 0.5) +
  scale_y_continuous(breaks = c(0, 1)) +
  labs(title = "Speaker preference by age",
       x = "Age (years)", 
       y = "Speaker preference")
```

```{r DV2 logistic model}
DV2_model <- stan_glm(reasoning~age, family=gaussian(), data=pp_data)
```

```{r visualize DV2 primary logistic model}
#Still have to filter out reasoning level 4
DV2_p.y.fit <- fitted(DV2_model)
  
ggplot(pp_data, aes(x=age)) +
  geom_point(aes(y=reasoning), size=2, shape=1) +
  geom_jitter(aes(y=reasoning), width=0.03, height=0.03, alpha=0.3) +
  geom_smooth(aes(y=DV2_p.y.fit), size=1, alpha=0.5) +
  scale_y_continuous(breaks=c(0, 1)) +
  labs(title="Reasoning as a funtion of age",x="age (years)", y="reasoning") +
  theme_classic()
```

NOTE: Not sure if the following code chunks are useful...

```{r Bayes factor 2vs3}

#Calculate a Bayes factor to compare the mean preference of 2- and 3-year olds.

BF2vs3 <- ttestBF(x=pp_data$speaker_preference[pp_data$age==2], y=pp_data$speaker_preference[pp_data$age==3], paired=FALSE)

BF2vs3

```

```{r Bayes factor 3vs4}

#Calculate a Bayes factor to compare the mean preference of 3- and 4-year olds.

BF3vs4 <- ttestBF(x=pp_data$speaker_preference[pp_data$age==3], y=pp_data$speaker_preference[pp_data$age==4], paired=FALSE)

BF3vs4

```

```{r Bayes factor 2vs4}

#Calculate a Bayes factor to compare the mean preference of 2- and 4-year olds.

BF2vs4 <- ttestBF(x=pp_data$speaker_preference[pp_data$age==2], y=pp_data$speaker_preference[pp_data$age==4], paired=FALSE)

BF2vs4

```

